### ISSUE TITLE
insured value in UPS provider

### ISSUE THREAD

**Issue by kylewest** [kylewest/DotNetShipping#1]

**Comment by szuranski** [comment]
I am passing in a value of 150 for the insuredValue parameter in the packages.Add method. If I use the  shipping calculator at [UPS Shipping Calculator](https://wwwapps.ups.com/ctc/request?loc=en_US) there is a $2.70 declared value fee added to the total. The shipment rate I get back after calling the GetRates method is exactly $2.70 less. It appears adding the isurance cost to the total has not been implemented. Is my assumption correct?

**Comment by kylewest** [comment]
UPS now properly handles package insured value. If you are still having issues with it please post a sample package.
