### ISSUE TITLE
"rates" is ambiguous?

### ISSUE THREAD

**Issue by dotNetNoob** [kylewest/DotNetShipping#14]
Hi: Sorry for the noob question, but I'm trying to follow your sample and I'm getting a compile error in VS2012:

Error   1   'Rates' is ambiguous because multiple kinds of members with this name exist in class 'DotNetShipping.Shipment'.

When I let intellisense pull up the methods for "shipment", "rates" is not in there? Here's a screencap of my code:

![untitled-1](https://f.cloud.github.com/assets/5372584/1072489/890d48a4-1492-11e3-8ec4-1c3bb84a1227.jpg)

**Comment by rlamunoz** [comment]
It happens to me with the new version and using FedEx

**Comment by MaxVerro** [comment]
I had this problem in one of my MVC project. My EF Entities reflected the table name Shipment and Rate from my database. This came in conflict with the class name from the DotNetShipping project and just like you it gave me the ambiguous error. In C# you can easily fix in 2 way:
1)  Adding the full reference path namespace.class when calling the class
2) In your namespace declaration you can add : using DotNetShippingPackage = DotNetShipping.Package

**Comment by kylewest** [comment]
Thanks @MaxVerro!
