### ISSUE TITLE
UPS delivery date for ground

### ISSUE THREAD

**Issue by dotNetNoob** [kylewest/DotNetShipping#17]
Hi: I'm noticing that the "deliveryDate" returned for UPS ground shows "12/31/9999" whereas all the Air rates have correct delivery dates in them.

I vaguely remember when I was trying to integrate expected delivery dates (several years ago) that the Rating API didn't return anything for ground, and you had to use the Time-In-Transit API instead.

Just curious if this in fact still true, and if anyone has attempted to integrate accurate delivery dates for UPS ground shipping into this project? (if not, and I'm correct that it needs to be implemented, I might be able to fork it in)

**Comment by happyiphone** [comment]
This link provides more information on this subject:

https://developerkitcommunity.ups.com/index.php/Special:AWCforum/st/id152
