### ISSUE TITLE
Only getting one FedEx rate

### ISSUE THREAD

**Issue by KevinVanGit** [kylewest/DotNetShipping#34]
When I run the sample app, I only get one rate (FedEx Ground) instead of all the options. Is this because I am running against FedEx test or am I missing something?

**Comment by KevinVanGit** [comment]
I found I get multiple results if I use only one package, but I get only ground when use multiple packages. Not sure why, but I believe this is expected. I can pull rates for each package individually and I think I am all set.

**Comment by kylewest** [comment]
Can you show me your packages? All I can think of is you're exceeding the max size/weight for air. Also note that sizes are in inches and weight is in pounds. The code below gets me both ground and air for multiple packages:

```cs
var packages = new List<Package>();
packages.Add(new Package(12, 12, 12, 35, 150)); // length, width, height, weight, insured value
packages.Add(new Package(4, 4, 6, 15, 250));
```

Kyle
