### ISSUE TITLE
Fedex UK destination addresses return no rates

### ISSUE THREAD

**Issue by cbotha24** [kylewest/DotNetShipping#36]
UK Destination addresses result in a rate type of INTERNATIONAL_FIRST which is not included in the _serviceCodes Dictionary in the FedexProvider. This results in an exception being thrown when the rate is added and no rates being added to the shipment.

**Comment by kylewest** [comment]
Can you please provide sample code to recreate this issue? I just tried a UK address and did not have any issues. Thanks,

Kyle
