### ISSUE TITLE
UPS negotiated rates

### ISSUE THREAD

**Issue by dotNetNoob** [kylewest/DotNetShipping#47]
I saw that bmcdavid added some overloads for UPS negotiated rates, but am not sure if they were ever incorporated into the codebase?

**Comment by jeffmowens** [comment]
This just needs to be added in the RatingServiceSelection / Request / Shipment / element.
<RateInformation>
		<NegotiatedRatesIndicator/>
</RateInformation>

**Comment by kylewest** [comment]
Pull request #32 had to be merged manually. It has been merged and released to the NuGet feed as version `0.9.4.51`.
