### ISSUE TITLE
AppVeyor build fails on Pull Requests

### ISSUE THREAD

**Issue by Soulfire86** [kylewest/DotNetShipping#48]
@kylewest Not sure if you already knew this, but I looked into why the build fails on every PR and it turns out that it is because the Environment Variables are encrypted, and that by design AppVeyor won't use secured variables when building on a Pull Request since it could be a security risk.

So, I wanted to throw out 2 options I could see off the top of my head:
1) In the settings, isn't there a way to just to not auto build on PRs?
2) Just use some unencrypted credentials that are all just dev/test creds for each provider?

**Comment by kylewest** [comment]
Makes sense, someone could add a test that prints out the variables and see them in plain text. probably best to just disable the builds unless there are published test account credentials for the providers (I don't think there are).

Kyle

**Comment by Soulfire86** [comment]
Yeah, it's be awesome to have tests run on PRs but just doesn't seem easy to do here where credentials are needed.

I don't think I have access to turn this off, but it should be in the Webhooks & Services part of the settings for the repo:

![image](https://cloud.githubusercontent.com/assets/234468/15021584/ae9e9056-11f5-11e6-9be8-2615671cab89.png)

**Comment by kylewest** [comment]
@Soulfire86 thanks for all the info. I disabled that in our settings. should be good to go now.
