### ISSUE TITLE
UPS International rate is not correct

### ISSUE THREAD

**Issue by amart7** [kylewest/DotNetShipping#58]
@kylewest 
For address:
 InternationalAddress = new DotNetShipping.Address("345A Forbes Road Zone 6 -  Meadowlands", "", "", "Johannesburg", "", "1852", "ZA");

it returns incorrect UPS shipping rate.
Package weight: 1.4 pounds
From address:
DomesticAddress = new DotNetShipping.Address("3701 Algonquin Road", "", "", "Rolling Meadows", "IL", "60008", "US");
![southafrica](https://cloud.githubusercontent.com/assets/13951627/22220375/0b161aae-e174-11e6-9567-843cc8fdb95a.PNG)

**Comment by kylewest** [comment]
Which rate is incorrect and what is the correct amount? Some things to check:

1. Are you using negotiated rates?
2. Have you implemented an `IRateAdjuster` that is manipulating the rates?

I used the same addresses and got different rates but I also don't know your package dimensions or insured value.

![screenshot-2017-01-24-at-09-44-22](https://cloud.githubusercontent.com/assets/6247/22251695/baaf7c26-e219-11e6-8d29-abe16462cdec.png)

```csharp
var packages = new List<Package>();
packages.Add(new Package(12, 12, 4, 1.4M, 0));

var origin = new DotNetShipping.Address("3701 Algonquin Road", "", "", "Rolling Meadows", "IL", "60008", "US");
var destination = new DotNetShipping.Address("345A Forbes Road Zone 6 - Meadowlands", "", "", "Johannesburg", "", "1852", "ZA");
```

**Comment by amart7** [comment]
@kylewest  
Do you think it costs $200+ to send 1.4 pounds package to South Africa?
Answers: 1. I am not using negotiated rate.
2. Adjuster IRateAdjuster is not used/implemented.

Package:
private readonly Package PackageInternational;
PackageInternational = new Package(13, 1, 2, (decimal)1.4, 0);
![image](https://cloud.githubusercontent.com/assets/13951627/22257281/30aea600-e223-11e6-9d9a-cc56b4567b71.png)

**Comment by amart7** [comment]
@kylewest 
By the way correct rate should be $87.22
![image](https://cloud.githubusercontent.com/assets/13951627/22258100/e8c71fea-e225-11e6-9ff8-e898af4a2eb9.png)

**Comment by kylewest** [comment]
I have no idea how much it costs to ship to south africa, but yes it looks expensive: 

![screenshot-2017-01-24-at-12-14-49](https://cloud.githubusercontent.com/assets/6247/22258251/d42b42ce-e22e-11e6-8d1c-687ea4093eac.png)

**Comment by kylewest** [comment]
Your screenshot shows:

* No dimensions which can dramatically change the rate.
* Negotiated rate which also dramatically changes the rate. I asked if you were using negotiated rates and you said no. Set `UseNegotiatedRates = true` and you should see a difference.
