### ISSUE TITLE
Not able to get International rate

### ISSUE THREAD

**Issue by amart7** [kylewest/DotNetShipping#59]
@kylewest 
I am not able to get International rate for address:
private readonly DotNetShipping.Address InternationalAddress;
InternationalAddress = new DotNetShipping.Address("General Pardinas, 72 2 A", "", "", "Madrid", "", "28006", "ES");
From address:
DomesticAddress = new DotNetShipping.Address("3701 Algonquin Road", "", "", "Rolling Meadows", "IL", "60008", "US");
packagesInternational = new List<Package>();
packagesInternational.Add(new Package(0, 0, 0, (decimal)(23/16), 0));
packagesInternational.Add(new Package(0, 0, 0, (decimal)(14/16), 0));

![image](https://cloud.githubusercontent.com/assets/13951627/22262041/f019bbb8-e234-11e6-9038-f5025faa9efb.png)

However I was able to get International rate on official UPS web site:

![image](https://cloud.githubusercontent.com/assets/13951627/22262349/301d0aca-e236-11e6-9fc5-1be36c329a98.png)

**Comment by kylewest** [comment]
Just a guess (not at computer) ... you can't have a package without dimensions. Try setting length, width, height to at least 1.
