### ISSUE TITLE
USPS rating engine does not handle 5 + 4 zip codes

### ISSUE THREAD

**Issue by pshaff** [kylewest/DotNetShipping#60]
Would it be possible to automatically shorten US zip codes that have 9 digits for the USPS provider?  As I see it today, I lose the USPS rates when a 9 digit zip code is entered.

**Comment by kylewest** [comment]
sure. should be a pretty easy implementation. you able to send me a pull request?

**Comment by Soulfire86** [comment]
Handled by #63 

Thanks @pshaff !

**Comment by kylewest** [comment]
Deployed to NuGet v0.9.5.77
