### ISSUE TITLE
UPS Rates Not being returned

### ISSUE THREAD

**Issue by mathis1337** [kylewest/DotNetShipping#61]
I have copied the code exactly from test page and I am not getting anything back. Is my UPS license number my account number, or access key? Mind you I have tried both. I am using Origin zip of 79403 and destination of 34769. Any help is appreciated it. here Is what I have.

NameValueCollection appSettings = ConfigurationManager.AppSettings;

string upsLicenseNumber = appSettings[""]; //removed for security reasons
string upsUserId = appSettings[""]; //removed for security reasons
string upsPassword = appSettings[""]; //removed for security reasons

var packages = new List<Package>();
//packages.Add(new Package(12, 12, 12, 35, 150));
packages.Add(new Package(6, 6, 6, 2, 149));

var origin = new DotNetShipping.Address("", "", "79403", "US");
var destination = new DotNetShipping.Address("", "", "34769", "US"); // US Address

var rateManager = new RateManager();

rateManager.AddProvider(new UPSProvider(upsLicenseNumber, upsUserId, upsPassword));

Shipment shipment = rateManager.GetRates(origin, destination, packages);

foreach (Rate rate in shipment.Rates)
{
	Console.WriteLine(rate.ToString());
}

**Comment by mathis1337** [comment]
Nevermind, figured it out, however, I don't see SurePost as an option. Is this not included in here?

**Comment by kylewest** [comment]
Is your code compiling? Should be `var packages = new List<Package>();`

**Comment by kylewest** [comment]
SmartPost is it's own provider ... and a FedEx thing. 

https://github.com/kylewest/DotNetShipping/pull/51

**Comment by mathis1337** [comment]
No I said SurePost. That is  UPS not fedex feature.

**Comment by kylewest** [comment]
Never heard of it. I'm sure it can be implemented. Send me a pull request!
