### ISSUE TITLE
Address in Spain does not return UPS rate

### ISSUE THREAD

**Issue by amart7** [kylewest/DotNetShipping#65]
Have problem specifically with Spain.
Address 1 in Madrid, Spain, weight = 37 ounces: 
Address 2 in Barcelona, Spain weight = 144 ounces: 
            InternationalAddress9 = new DotNetShipping.Address("C/General Pardinas, 72 2 A", "", "", "Madrid", "", "28006", "ES");
            InternationalAddress10 = new DotNetShipping.Address("C/Badajoz 73-77", "", "", "Barcelona", "", "E-08005", "ES");

Ship-from: DomesticAddress = new DotNetShipping.Address("3701 Algonquin Road", "", "", "Rolling Meadows", "IL", "60008", "US");

UseNegotiatedRates = true;

Let me know.

**Comment by kylewest** [comment]
Are you entering the weight as `37` and `144`? It should be a decimal in pounds: `2.31` and `9`.

Also, I don't think `E-08005` is a valid postal code.

**Comment by amart7** [comment]
@kylewest I am entering weight as decimal((decimal)37/(decimal)16).. Where you able to get rate for Madrid?

**Comment by amart7** [comment]
@kylewest  
I was debugging and found that PostalCode is not sent for Internationaladdresses
see line 201 in "UPSProvider.cs" file and see attached file. Why do we not allow PostalCode for International Address (ship-to)?
![debugmadrid](https://cloud.githubusercontent.com/assets/13951627/22992076/2a1e1344-f384-11e6-8746-f780b667d5b7.PNG)
