### ISSUE TITLE
Get XML Request from request

### ISSUE THREAD

**Issue by amart7** [kylewest/DotNetShipping#66]
Hi! When I talk to UPS Tech support they asked to provide only XML Request to them. How can I get XML Request from code? Optional: how to get XML response? Thank you!

**Comment by kylewest** [comment]
Easiest way is to use [Fiddler](http://www.telerik.com/fiddler) to inspect the traffic to and from your development machine. 

Alternatively, you could set a debug breakpoint somewhere in [here](https://github.com/kylewest/DotNetShipping/blob/master/DotNetShipping/ShippingProviders/UPSProvider.cs#L252) and step through the request and response.

Kyle
