### ISSUE TITLE
Postal code of International address (ship-to) is not sent in request

### ISSUE THREAD

**Issue by amart7** [kylewest/DotNetShipping#67]
@kylewest 
I was debugging and found that PostalCode was not sent for International addresses
see line 201 in "UPSProvider.cs" file and see attached file. Why do we not allow PostalCode for International Address (ship-to)?
![debugmadrid](https://cloud.githubusercontent.com/assets/13951627/22992257/be66af0c-f384-11e6-8cd0-5ef85313dd08.PNG)

**Comment by amart7** [comment]
@kylewest 
I cannot get shipping rate for international address because zip code is not sent. Can we send zip code for International address?

**Comment by kylewest** [comment]
sure. send me a pull request. Thanks.

**Comment by amart7** [comment]
@kylewest I am not able to send pull request. Are you able to change on your side?
![image](https://cloud.githubusercontent.com/assets/13951627/24157368/2fd3f052-0e27-11e7-83c5-b27ca813e3cc.png)


![image](https://cloud.githubusercontent.com/assets/13951627/24157309/0f0db6d2-0e27-11e7-9c0e-f49f18510ca0.png)

**Comment by amart7** [comment]
@kylewest I do not have permission to submit pull request. Cabn you give me permission or modify cvode based on my notes?

**Comment by amart7** [comment]
@kylewest  finally I was able to create pull request: 
https://github.com/kylewest/DotNetShipping/pull/71

**Comment by amart7** [comment]
@kylewest Sorry, how to add you as assignee/reviewr to my pull request? https://github.com/kylewest/DotNetShipping/pull/71

**Comment by Soulfire86** [comment]
I'll try to take a look tonight or tomorrow unless kyle gets to it first.
