### ISSUE TITLE
Nuget package doesn't work in dot net 4.5

### ISSUE THREAD

**Issue by solmead** [kylewest/DotNetShipping#72]
The NuGet package does not contain any assembly refrencesthat are compatible with the .NET Framework Version 4.5. 
There should be something in it's description if it only supports specific versions.
Could it be updated to support 4.5?

**Comment by kylewest** [comment]
are you referring to .net 4.5.0? I see 4.5.2 in project properties. I changed to 4.5.0 and it built and tests were run successfully so it should work with 4.5.0.

To be honest though, I'm not entirely sure how best to do framework targeting in a package. Would be happy to merge a pull request if you figure it out.

Kyle

**Comment by SANOZUKESAKARA** [comment]
Hi, I changed from 4.5.2 to 4.5.

I still get errror:

Error	22	'DotNetShipping.ShippingProviders.UPSProvider.DEVELOPMENT_RATES_URL' is a 'field' but is used like a 'type'	C:\dev\other project\DotNetShipping-master\DotNetShipping-master\DotNetShipping\ShippingProviders\UPSProvider.cs	129	75	DotNetShipping
Error	21	'DotNetShipping.ShippingProviders.UPSProvider.UseProduction' is a 'property' but is used like a 'type'	C:\dev\other project\DotNetShipping-master\DotNetShipping-master\DotNetShipping\ShippingProviders\UPSProvider.cs	129	36	DotNetShipping
Error	18	; expected	C:\dev\other project\DotNetShipping-master\DotNetShipping-master\DotNetShipping\ShippingProviders\UPSProvider.cs	129	33	DotNetShipping
Error	19	; expected	C:\dev\other project\DotNetShipping-master\DotNetShipping-master\DotNetShipping\ShippingProviders\UPSProvider.cs	129	73	DotNetShipping
Error	20	Invalid token ';' in class, struct, or interface member declaration	C:\dev\other project\DotNetShipping-master\DotNetShipping-master\DotNetShipping\ShippingProviders\UPSProvider.cs	129	96	DotNetShipping
Error	23	The call is ambiguous between the following methods or properties: 'DotNetShipping.Extensions.ToUpsShipCode(string)' and 'DotNetShipping.Extensions.ToUpsShipCode(string)'	C:\dev\other project\DotNetShipping-master\DotNetShipping-master\DotNetShipping\ShippingProviders\UPSProvider.cs	217	51	DotNetShipping
Error	14	The type or namespace name 'IRateAdjuster' could not be found (are you missing a using directive or an assembly reference?)	C:\dev\other project\DotNetShipping-master\DotNetShipping-master\SampleApp\PercentageRateAdjuster.cs	3	43	SampleApp
Error	16	The type or namespace name 'Rate' could not be found (are you missing a using directive or an assembly reference?)	C:\dev\other project\DotNetShipping-master\DotNetShipping-master\SampleApp\PercentageRateAdjuster.cs	12	16	SampleApp
Error	17	The type or namespace name 'Rate' could not be found (are you missing a using directive or an assembly reference?)	C:\dev\other project\DotNetShipping-master\DotNetShipping-master\SampleApp\PercentageRateAdjuster.cs	12	32	SampleApp
Error	15	The type or namespace name 'ShippingProviders' does not exist in the namespace 'DotNetShipping' (are you missing an assembly reference?)	C:\dev\other project\DotNetShipping-master\DotNetShipping-master\SampleApp\Program.cs	5	22	SampleApp
Error	4	Unexpected character '$'	C:\dev\other project\DotNetShipping-master\DotNetShipping-master\DotNetShipping.Tests\Features\UPSRates.cs	48	29	DotNetShipping.Tests
Error	5	Unexpected character '$'	C:\dev\other project\DotNetShipping-master\DotNetShipping-master\DotNetShipping.Tests\Features\UPSRates.cs	71	29	DotNetShipping.Tests
Error	6	Unexpected character '$'	C:\dev\other project\DotNetShipping-master\DotNetShipping-master\DotNetShipping.Tests\Features\UPSRates.cs	94	29	DotNetShipping.Tests
Error	7	Unexpected character '$'	C:\dev\other project\DotNetShipping-master\DotNetShipping-master\DotNetShipping.Tests\Features\UPSRates.cs	117	29	DotNetShipping.Tests
Error	8	Unexpected character '$'	C:\dev\other project\DotNetShipping-master\DotNetShipping-master\DotNetShipping.Tests\Features\UPSRates.cs	143	29	DotNetShipping.Tests
Error	9	Unexpected character '$'	C:\dev\other project\DotNetShipping-master\DotNetShipping-master\DotNetShipping.Tests\Features\UPSRates.cs	166	29	DotNetShipping.Tests
Error	10	Unexpected character '$'	C:\dev\other project\DotNetShipping-master\DotNetShipping-master\DotNetShipping.Tests\Features\UPSRates.cs	189	29	DotNetShipping.Tests

**Comment by kylewest** [comment]
@SANOZUKESAKARA @solmead 

I didn't have the same issue. I changed the targeting to .net 4.5 and will publish a new NuGet package shortly.

**Comment by kylewest** [comment]
v0.9.5.90 now available on NuGet.
