### ISSUE TITLE
Still being maintained?

### ISSUE THREAD

**Issue by ahwm** [kylewest/DotNetShipping#89]
It looks like there are a lot of open issues that haven't been addressed in over a year - almost 2 years in some cases. Is this project still being maintained?

I'd be open to helping out some

**Comment by alexeybusygin** [comment]
Hey! I am maintaining a fork here: https://github.com/alexeybusygin/ShippingRates
It's .Net Standard 2.0 and with the latest FedEx API version. You might be interested.

**Comment by kylewest** [comment]
let me know if you guys would like to take over, or I can just update the readme to point at your repo.

**Comment by alexeybusygin** [comment]
@kylewest That would be great if you can add the repo link to the readme. And I would like to thank you for the DotNetShipping, we've been using it for years and it's fantastic! :blush:

**Comment by Soulfire86** [comment]
@alexeybusygin Happened to check here and realized I had been granted repo permissions back in the day before I too dropped off the planet :) 

I've edited the readme to point to your maintained fork! Thanks a bunch! I've had 0 need for this in years, but super cool to see it's been taken and is running well!

**Comment by alexeybusygin** [comment]
@Soulfire86 Great, thanks! :)
